### ISSUE TITLE
Possible to retrieve wemo status?

### ISSUE THREAD

**Issue by mikeyoung83** [amcolash/PebbleIoT#1]
Just been tinkering around with this project. Cool stuff.
Got it toggling on/off a wemo switch without issue.

Wondering if it's possible to retrieve the on/off status of a given switch and have it displayed?

**Comment by amcolash** [comment]
Hey Mike,

As of this point in time the IFTTT platform only supports activating things
(i.e. toggle, off, on) but not getting status. I think that would be cool
as well but I don't think it is currently in the scope of this project
which is just a bridging of pebble <==> IFTTT.

If you are a developer and interested in working with the api, I suggest
checking out http://developers.belkin.com/wemo/sdk and forking the source
code I have currently (PebbleJS) https://github.com/amcolash/IoT-Buddy/.

Good luck,
Andrew

**Comment by mikeyoung83** [comment]
Thanks!
