### ISSUE TITLE
Support for IFTTT Maker Channel Values

### ISSUE THREAD

**Issue by ozgurakan** [amcolash/PebbleIoT#2]
While tracking number of cups of water I drink, I would like to be able to pass number as value to IFTTT channel. On the IoT-Buddy, I could create two entries; one of them with `value1=1` other `value1=2`. This way I could track number value on the same maker channel.

**Comment by amcolash** [comment]
I just updated the app to support sending of value1 to IFTTT. Let me know what you think - it was working with a test event I made. Hope this helps you out!
