### ISSUE TITLE
2.1: Key length allowed seems insufficient

### ISSUE THREAD

**Issue by m-p-3** [amcolash/PebbleIoT#3]
`#define KEY_LENGTH 40`

I was unable to insert my IFTTT Maker key, as it exceeds 40 characters. I'm not sure if the code for the new Pebble app (which I think is in C) would break if provided with a variable key length to an array.

**Comment by amcolash** [comment]
Hi, yeah changing that _could_ break things. I can change it, but I need to know how long your key is. How long is your key right now?

**Comment by amcolash** [comment]
P.S. mine is 22 characters, so I am a bit shocked it is that much larger

**Comment by m-p-3** [comment]
I was quite surprised too, I guess IFTTT had to make their keys longer after a while.

**Comment by m-p-3** [comment]
Oh and my key is currently 43 characters long.

**Comment by amcolash** [comment]
So close! I will bump it to 60 characters some time in the next few days when I get some time

**Comment by amcolash** [comment]
I bumped to 50 as I was getting pretty close to some internal limits. If things are still not working though we can look deeper into the issue. Let me know if the fix I just pushed a bit ago works :) I update the app in the app store too.
